version: "3.9"

services:
  mongo:
    image: mongo:6.0-jammy
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db:cached
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 10s
      timeout: 3s
      retries: 3

  # server:
  #   build:
  #     context: .
  #   ports:
  #     - 9001:9001
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./:/app:delegated
  #     - '/app/node_modules'   # Specialized treatment for all types of diseases with the node_modules package
  #   depends_on:
  #     - mongo

volumes:
  mongo-data: